entryPoints:
  https:
    address: :443
  postgresql:
    address: :5432
  redis:
    address: :6379

api:
  dashboard: true
  insecure: false

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic

# ログレベルの設定
# https://doc.traefik.io/traefik/observability/logs/
log:
  level: ERROR
