name: Deploy(build-only)

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: repository
        name: Get repository name
        run: echo "name=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Container Image
        uses: docker/bake-action@v4
        env:
          OWNER: ${{ github.repository_owner }}
          REPOSITORY_NAME: ${{ steps.repository.outputs.name }}
          API_FQDN: ${{ vars.API_FQDN }}
          OAUTH2_AUDIENCE: ${{ vars.OAUTH2_AUDIENCE }}
          OAUTH2_CLIENT_ID: ${{ vars.OAUTH2_CLIENT_ID }}
          OAUTH2_ISSUER_FQDN: ${{ vars.OAUTH2_ISSUER_FQDN }}
          TAG: ${{ github.ref_name }}
        with:
          push: true
          files: docker-bake.hcl
